### ISSUE TITLE
Test strain relationship

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/forecast.vocs#47]
Consider evaluating how it is best to model strain relationships for forecasting (independent, dependent, or pooled).

**Comment by seabbs** [comment]
In #48 added ability to look at this.

**Comment by jbracher** [comment]
Is this related to #38? I made a comment there with essentially the same question. Consider this the most interesting question in terms of model structure.

**Comment by seabbs** [comment]
Yes. Added comments there and I agree this is definitely the interesting aspect.
